author: Hengxin # 作者
description: Henxin's blog
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

comment: gitment

# gitment config
gitment_owner: hengxinchou
gitment_repo: hengxinchou.github.io
gitment_oauth_id: 73559b1d39c3b8a1d23b
gitment_oauth_secret: 93ce94f34ac98249f283224e4916ed57df7fe771

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 

# disqus config
disqus_shortname: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: /image/avatar.jpg
  description: "The end is always near."
  # weibo_username: yanm1ng
  # twitter_username: yanm1ng
  github_username: hengxinchou
  # zhihu_username: yummy1121
  # douban_username: yanm1ng
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
